name: Deploy to InfinityFree

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}   # permite rodar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}   # ex.: /whereuwatch.com/htdocs/
          protocol: ftps
          port: 21
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git**
            **/.github/**
            **/node_modules/**
            **/.env*
            **/README.md
            **/.DS_Store
          dangerous-clean-slate: false
